export const UserActionTypes = {
    GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
    POST_DATA_SUCCESS: 'POST_DATA_SUCCESS',
    PUT_DATA_SUCCESS: 'PUT_DATA_SUCCESS',
    DELETE_DATA_SUCCESS: ' DELETE_DATA_SUCCESS',
}